OpenNMS/opennms-js

- src/dao/AlarmDAO.ts
- src/model/OnmsAlarm.ts
- src/model/OnmsMemo.ts
- test/dao/AlarmDAO.spec.ts
- test/rest/21.0.0/get/api/v2/alarms/82416.json
- test/rest/MockHTTP21.ts
Update the alarm model to include the journal and sticky memos.
> feat(alarms): expose the sticky and journal memos

- src/CLI.ts
- src/api/IOnmsHTTP.ts
- src/api/OnmsError.ts
- src/api/OnmsHTTPOptions.ts
- src/dao/AlarmDAO.ts
- src/rest/AbstractHTTP.ts
- src/rest/AxiosHTTP.ts
- src/rest/GrafanaHTTP.ts
- test/dao/AlarmDAO.spec.ts
- test/rest/MockHTTP19.ts
- test/rest/MockHTTP21.ts
Support creating, updating, and deleting alarm tickets.
also:
* add POST support to the HTTP API
* do more useful error handling on ReST failures
> HZN-1119: add Alarm ticket create/update/delete

- src/CLI.ts
- src/api/IOnmsHTTP.ts
- src/dao/AlarmDAO.ts
- src/rest/AbstractHTTP.ts
- src/rest/AxiosHTTP.ts
- src/rest/GrafanaHTTP.ts
- test/dao/AlarmDAO.spec.ts
- test/rest/MockHTTP19.ts
- test/rest/MockHTTP21.ts
JIRA: https://issues.opennms.org/browse/JS-7
> feat(alarms): add support for manipulating journal and sticky memos

- src/dao/AlarmDAO.ts
- src/dao/EventDAO.ts
- src/rest/AbstractHTTP.ts
- src/rest/JsonTransformer.ts
- src/rest/XmlTransformer.ts
- test/dao/AlarmDAO.spec.ts
* JIRA: https://issues.opennms.org/browse/JS-10
> JS-10: Handle single alarm (xml) result properly

- README.md
- package.json
- yarn.lock
* JIRA: https://issues.opennms.org/browse/JS-12
> JS-12: Make breakpoints work

- src/api/SearchProperty.ts
- src/api/SearchPropertyType.ts
- src/dao/AbstractDAO.ts
This is some additional work on top of https://github.com/OpenNMS/opennms-js/pull/6 required for JS-11 to be complete.
* JIRA: https://issues.opennms.org/browse/JS-11
> JS-11: Include comparators and values (JS-11)

- src/Client.ts
- src/api/ServerMetadata.ts
- src/api/TicketerConfig.ts
* JIRA: https://issues.opennms.org/browse/JS-17
Depends on https://github.com/OpenNMS/opennms/pull/1631
> JS-17: Include ticketer configuration

- src/dao/AbstractDAO.ts
- src/dao/AlarmDAO.ts
- src/dao/EventDAO.ts
- src/dao/ISearchPropertyAccessor.ts
- src/dao/NodeDAO.ts
- src/dao/PropertiesCache.ts
- src/dao/V2FilterProcessor.ts
- src/internal/Util.ts
- src/rest/AxiosHTTP.ts
- src/rest/GrafanaHTTP.ts
- test/dao/V2FilterProcessor.spec.ts
- test/internal/Util.spec.ts
This adds more complex null value handling to the V2FilterProcessor:
* JIRA: https://issues.opennms.org/browse/JS-20
This will still not fully work, due to the following issue: 
* https://issues.opennms.org/browse/NMS-9578
> JS-20: Add more complex null value handling for v2

- src/api/SearchProperty.ts
- src/dao/AbstractDAO.ts
- src/dao/IValueProvider.ts
* JIRA: https://issues.opennms.org/browse/JS-22
Only works if https://github.com/OpenNMS/opennms/pull/1638 (HZN-1098) is merged.
As mentioned in the PR above the result from `<endpoint>/properties/<id>` is not sorted. 
If sorting is not added there, we should probably sort the values in the client. 
Please keep that in mind before merging.
> feat(dao): Add capability to fetch values from alarm v2 endpoint (JS-22)

- src/dao/AlarmDAO.ts
* JIRA: https://issues.opennms.org/browse/JS-24
> fix(dao): Map troubleTicketState properly (JS-24)

- src/dao/AlarmDAO.ts
- src/model/OnmsAlarm.ts
* JIRA: https://issues.opennms.org/browse/JS-23
Depends on https://github.com/OpenNMS/opennms/pull/1648
> feat(dao): Include troubleTicketLink if defined (JS-23)

- src/api/OnmsServer.ts
- src/dao/AlarmDAO.ts
- src/model/OnmsAlarm.ts
- test/dao/AlarmDAO.spec.ts
JIRA: https://issues.opennms.org/browse/HELM-55
> feat(alarms): expose a link to the alarm details page (HELM-55)

- src/CLI.ts
This had me stumped for a while, so I suppose a quick update of the example filter might be useful to others as well.
> fix(cli): Valid example for node label searches

- src/API.ts
- src/dao/AlarmDAO.ts
- src/model/OnmsAlarm.ts
- src/model/OnmsAlarmSummary.ts
- test/dao/AlarmDAO.spec.ts
- test/rest/23.0.0/get/api/v2/alarms/8.json
- test/rest/MockHTTP23.ts
This change adds an AlarmSummaryDTO for adding related alarms to an Alarm.
This was initially required for Alarm Correlation.
JIRA: https://issues.opennms.org/browse/HZN-1328
> HZN-1328 AlarmSummaryDTO for Correlated Alarms

- src/dao/SituationFeedbackDAO.ts
- test/dao/SituationFeedbackDAO.spec.ts
Serialize the FeedbackType as a simple string for the ReST API.
> fix(feedback): Serialize the enum as a string

- src/dao/AlarmDAO.ts
- src/model/OnmsAlarm.ts
- src/model/OnmsAlarmSummary.ts
- test/dao/AlarmDAO.spec.ts
- test/rest/23.0.0/get/api/v2/alarms/243.json
- test/rest/MockHTTP23.ts
This PR adds the following attributes to
OnmsAlarm:
inSituation
affectedNodeCount
OnmsAlarmSummary:
label
logMessage
> feat(api): OCE-REST extend Alarm and summary

- src/dao/SituationFeedbackDAO.ts
- src/model/OnmsSituationFeedback.ts
- src/model/OnmsSituationFeedbackType.ts
- test/dao/SituationFeedbackDAO.spec.ts
- test/rest/24.0.0/get/rest/situation-feedback/616.json
- test/rest/24.0.0/get/rest/situation-feedback/tags.json
- test/rest/MockHTTP24.ts
This PR adds support for tags and root cause in the situation feedback.
Additionally, existing tags can be querired from the datasource to assist front end work.
JIRA: https://issues.opennms.org/browse/HZN-1492
> feat(alarms): HZN-1492 : Add RootCause and Tags to SituationFeedback

- README.md
- src/CLI.ts
- src/api/Filter.ts
- src/api/IFilterProcessor.ts
- src/api/OrderBy.ts
- src/dao/V1FilterProcessor.ts
- src/dao/V2FilterProcessor.ts
- src/rest/AxiosHTTP.ts
- test/dao/V1FilterProcessor.spec.ts
- test/dao/V2FilterProcessor.spec.ts
Before we can support ordering in Helm, it needed to be added to OpenNMS.js.  This PR does 2 things:
1. adds support for query parameters with multiple values (including fixing Axios support to process them properly)
2. adds support for `orderBy=` and `order=` parameters on the Filter object
3. adds support for `orderBy=` and `order=` to the OpenNMS.js CLI
1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
2. update the JIRA link at the bottom of this comment to refer to the real issue number
3. prefix your commit messages with the issue number, if possible
One or more reviewers should be assigned to each PR.
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers …
> HELM-174: add support for `orderBy` and `order` in query params

- README.md
- src/dao/AlarmDAO.ts
- src/dao/EventDAO.ts
- src/dao/NodeDAO.ts
1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
2. update the JIRA link at the bottom of this comment to refer to the real issue number
3. prefix your commit messages with the issue number, if possible
One or more reviewers should be assigned to each PR.
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a …
> JS-45: fix handling of DAO results missing data

- package-lock.json
- package.json
- src/dao/AbstractDAO.ts
Does what it says on the box  :)
> Update to latest babel and typescript

- src/rest/AbstractHTTP.ts
- src/rest/GrafanaError.ts
This PR fixes response type handling if no configuration is passed through.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-232
* Continuous Integration: [Bamboo](https://bamboo.opennms.org/), [CircleCI](https://circleci.com/gh/OpenNMS/opennms-js)
> HELM-232: fix response type handling

- src/API.ts
- src/api/ServerMetadata.ts
- src/dao/FlowDAO.ts
This PR just makes some small changes to the ToS server metadata to conform to the style of the other properties.  Also sets the ToS minimum version to Horizon 28.0.0 and Meridian 2022.1.0 to match the expected location(s) of the ToS code.
> Minor ToS changes

- README.md
- docs-src/antora.yml
- package-lock.json
- package.json
- src/API.ts
- src/Client.ts
- src/dao/EventDAO.ts
- src/dao/MonitoredServiceDAO.ts
- src/dao/OutageDAO.ts
- src/dao/SnmpInterfaceDAO.ts
- src/model/OnmsEvent.ts
- src/model/OnmsIpInterface.ts
- src/model/OnmsOutage.ts
This PR adds DAOs for `api/v2/snmpinterfaces`, `api/v2/ifservices`, and `api/v2/outages`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-228
* Continuous Integration: [CircleCI](https://circleci.com/gh/OpenNMS/opennms-js)
> HELM-228: add SNMP interface, service, and outage support

- src/api/ServerMetadata.ts
Issue: https://issues.opennms.org/browse/JS-51
> JS-51: Add feature toggle for select resources endpoint

- local-site.yml
NMS-14666: Update all repos with link to new Antora UI bundle - updated reference to UI bundle to be the latest.
1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
2. update the JIRA link at the bottom of this comment to refer to the real issue number
3. prefix your commit messages with the issue number, if possible
One or more reviewers should be assigned to each PR.
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.
At that time, if you have commit access (are an …
> NMS-14666: Update all repos with link to new Antora UI bundle
